"""Tests for the requirements exporter (scripts/regen_requirements.py)."""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
_spec = importlib.util.spec_from_file_location(
    "regen_requirements", REPO_ROOT / "scripts" / "regen_requirements.py"
)
assert _spec and _spec.loader
regen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(regen)


def test_export_prod_excludes_dev_packages():
    text = regen.export(include_dev=False)
    assert text.startswith("# This file was autogenerated by uv")
    # pytest is a dev-only dependency; it must not appear in the prod set.
    assert "\npytest==" not in text


def test_export_dev_includes_dev_packages():
    text = regen.export(include_dev=True)
    assert "\npytest==" in text


def test_write_files_creates_both(tmp_path):
    regen.write_files(tmp_path)
    assert (tmp_path / "requirements.txt").is_file()
    assert (tmp_path / "requirements-dev.txt").is_file()
    assert "\npytest==" not in (tmp_path / "requirements.txt").read_text()
    assert "\npytest==" in (tmp_path / "requirements-dev.txt").read_text()


def test_stdout_mode_writes_pure_requirements(capsys):
    regen.main(["--stdout"])
    out = capsys.readouterr().out
    assert out.startswith("# This file was autogenerated by uv")
    assert "\npytest==" not in out  # prod-only default


def test_stdout_include_dev(capsys):
    regen.main(["--stdout", "--include-dev"])
    out = capsys.readouterr().out
    assert "\npytest==" in out


def test_include_dev_without_stdout_errors():
    with pytest.raises(SystemExit):
        regen.main(["--include-dev"])
