"""Type stubs for the hidapi (hid) C extension module."""

from typing import Any

def enumerate(vendor_id: int = 0, product_id: int = 0) -> list[dict[str, Any]]: ...

class device:  # noqa: N801 — matches the C extension's actual class name
    def open(self, vendor_id: int, product_id: int) -> None: ...
    def open_path(self, path: bytes) -> None: ...
    def close(self) -> None: ...
    def read(self, max_length: int, timeout_ms: int = 0) -> list[int]: ...
    def write(self, data: bytes | list[int]) -> int: ...
    def send_feature_report(self, data: bytes | list[int]) -> int: ...
    def get_feature_report(self, report_id: int, max_length: int) -> list[int]: ...
    def get_input_report(self, report_id: int, max_length: int) -> list[int]: ...
    def get_manufacturer_string(self) -> str: ...
    def get_product_string(self) -> str: ...
    def get_serial_number_string(self) -> str: ...
    def get_indexed_string(self, index: int) -> str: ...
    def get_report_descriptor(self) -> list[int]: ...
    def set_nonblocking(self, nonblock: int) -> int: ...
    def error(self) -> str | None: ...

def version_str() -> str: ...
